import React from 'react';
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Privacy Policy – Lineage',
  description:
    'Privacy Policy for the Lineage mobile app. Learn what data we collect, how we use it, and your rights.',
  keywords: [
    'privacy policy',
    'Lineage app',
    'chat',
    'Stream Chat',
    'Firebase Authentication',
    'Node.js backend',
    'OneSignal',
    'Expo',
  ],
};

export default function PrivacyPolicyPage() {
  return (
    <main className="px-6 py-10 max-w-3xl mx-auto">
      <h1 className="text-4xl font-bold mb-4">Privacy Policy for MyLineage</h1>
      <p className="text-sm text-gray-600 mb-8">Last updated: July 20, 2023</p>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">1. Introduction</h2>
        <p>
          MyLineage is a mobile app and web platform designed to help users
          manage and share their personal journey through customizable
          timelines and family trees.
        </p>
        <p>
          This Privacy Policy explains how MyLineage collects, uses, and
          protects your information when you use our app or visit our website.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">2. Information You Collect</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Personal Data:</strong> name, email address, profile picture (optional), and unique user ID generated by MyLineage.
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">3. How You Collect It</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>Forms:</strong> when you register, log in, or update your profile.
          </li>
          <li>
            <strong>Third Parties:</strong> through authentication (Firebase Auth) and chat integrations (Stream Chat).
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">4. Why You Collect It</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>To provide core app and website functionality.</li>
          <li>To improve and personalize your user experience.</li>
          <li>To communicate updates, support messages, and notifications.</li>
          <li>For marketing purposes, if you opt in.</li>
          <li>To comply with legal and regulatory obligations.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">5. Data Sharing and Disclosure</h2>
        <p>
          We may share your information with third-party service providers that are essential for core functionality, such as authentication, messaging, and notifications. We do not sell your personal data.
        </p>
        <ul className="list-disc list-inside space-y-2">
          <li>Authentication Services: Firebase Authentication</li>
          <li>Chat Services: Stream Chat</li>
          <li>Notification Services: OneSignal, Firebase (FCM)</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">6. How You Store and Protect Data</h2>
        <p>
          We store data on secure servers using encryption in transit (TLS) and
          at rest. Access to personal data is restricted to authorized
          personnel. We retain data only as long as necessary to fulfill the
          purposes outlined or as required by law.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">7. User Rights</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>Right to access, correct, or delete your personal data.</li>
          <li>Right to opt out of marketing communications.</li>
          <li>Right to data portability under GDPR.</li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">8. Cookies and Tracking Technologies</h2>
        <p>
          We do not use cookies, pixels, or any tracking technologies. We do not track user activity.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">9. Third-Party Services</h2>
        <ul className="list-disc list-inside space-y-2">
          <li>
            <strong>OneSignal:</strong> Push notifications. <a href="https://onesignal.com/privacy_policy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Privacy Policy</a>
          </li>
          <li>
            <strong>Firebase (FCM & Auth):</strong> Messaging and authentication. <a href="https://firebase.google.com/support/privacy" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Privacy Policy</a>
          </li>
          <li>
            <strong>Stream Chat:</strong> Real-time messaging. <a href="https://getstream.io/chat/privacy/" className="text-blue-600 hover:underline" target="_blank" rel="noopener noreferrer">Privacy Policy</a>
          </li>
        </ul>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">10. Children's Privacy</h2>
        <p>
          MyLineage is not intended for children under 13. We do not knowingly
          collect personal data from children under 13. If you believe we have
          inadvertently done so, please contact us.
        </p>
      </section>

      <section className="mb-6">
        <h2 className="text-2xl font-semibold mb-2">11. Changes to This Policy</h2>
        <p>
          We may update this Privacy Policy at any time. When changes are made,
          we will update the "Last updated" date and notify you via app
          notification or email.
        </p>
      </section>

      <section>
        <h2 className="text-2xl font-semibold mb-2">12. Contact Information</h2>
        <p>
          If you have questions or concerns about this policy, please email us
          at <a href="mailto:info@lineageproject.co" className="text-blue-600 hover:underline">info@lineageproject.co</a>.
        </p>
      </section>
    </main>
  );
}
